on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal